### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'getBuffer' of null

### ISSUE THREAD

**Issue by jamiltron** [aki77/atom-emacs-plus#26]
[Enter steps to reproduce below:]
1. Move the cursor anywhere in a document
2. type C-space

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [emacs-plus](https://github.com/aki77/atom-emacs-plus) package, v0.11.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of null

```
At /Users/jamiltron/.atom/packages/emacs-plus/lib/mark.coffee:24

TypeError: Cannot read property 'getBuffer' of null
    at Mark.activate (/Users/jamiltron/.atom/packages/emacs-plus/lib/mark.coffee:24:39)
    at Mark.activate (/Users/jamiltron/.atom/packages/emacs-plus/lib/mark.coffee:1:1)
    at Emacs.module.exports.Emacs.setMark (/Users/jamiltron/.atom/packages/emacs-plus/lib/emacs.coffee:295:24)
    at atom-text-editor.<anonymous> (/Users/jamiltron/.atom/packages/emacs-plus/lib/emacs.coffee:3:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:21.6.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
 12x -0:18 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
     -0:15.2.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:14.1.0 markdown-writer:insert-new-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:14.1.0 editor:newline (atom-text-editor.editor.emacs-plus.is-focused)
     -0:11 core:backspace (atom-text-editor.editor.emacs-plus.is-focused.autocomplete-active)
     -0:08.6.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused.autocomplete-active)
     -0:08.4.0 autocomplete-plus:confirm (atom-text-editor.editor.emacs-plus.is-focused.autocomplete-active)
     -0:07.6.0 core:move-left (atom-text-editor.editor.emacs-plus.is-focused)
     -0:06.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:05.8.0 editor:move-to-beginning-of-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:05.6.0 emacs-plus:set-mark (atom-text-editor.editor.emacs-plus.is-focused)
     -0:05.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
  3x -0:00.8.0 blur (atom-text-editor.editor.emacs-plus.is-focused)
     -0:00.2.0 editor:move-to-beginning-of-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:00.0 emacs-plus:set-mark (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-glsl",
      "linter-lua-findglobals",
      "linter-emscripten",
      "love-ide",
      "go-plus",
      "autocomplete-go",
      "builder-go",
      "go-get",
      "godoc",
      "gofmt",
      "gometalinter-linter",
      "gorename",
      "linter-cpplint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".o",
      "*.o"
    ],
    "projectHome": "/Users/jamiltron/Workspace",
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.4 (inactive)
arduino-toolbelt, v0.1.1 (inactive)
arduino-upload, v1.0.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-typescript, v10.1.7 (active)
atom-yeoman, v0.3.15 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-glsl, v0.2.3 (active)
autocomplete-go, v1.2.0 (inactive)
autocomplete-haskell, v0.6.7 (inactive)
autocomplete-love, v0.3.0 (active)
build-cargo, v0.19.0 (active)
build-cmake, v0.6.4 (active)
build-tools, v4.5.3 (active)
build-tools-make, v0.2.1 (active)
builder-go, v1.0.1 (inactive)
cargo-test-runner, v0.1.0 (inactive)
clang-format, v1.25.0 (active)
comment-dwim-light, v0.9.6 (active)
cpp-generator, v0.1.0 (inactive)
elm-format, v2.1.0 (active)
emacs-plus, v0.11.1 (active)
file-icons, v1.7.20 (active)
gcc-make-run, v0.2.9 (active)
git-control, v0.8.2 (inactive)
git-projects, v1.17.0 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (inactive)
go-plus, vundefined (inactive)
godoc, v1.1.0 (inactive)
gofmt, v1.2.0 (inactive)
gometalinter-linter, v1.2.2 (inactive)
gorename, v1.1.0 (inactive)
haskell-ghc-mod, v1.17.2 (inactive)
haskell-hoogle, v0.1.3 (inactive)
haskell-pointfree, v0.1.3 (active)
haskell-unicode-snippets, v0.1.1 (active)
haxe, v0.8.14 (active)
haxe-import, v1.2.1 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (active)
hyperclick-love, v0.4.0 (active)
ide-haskell, v1.8.1 (inactive)
ide-haskell-cabal, v1.6.4 (inactive)
ide-haskell-hasktags, v0.0.7 (inactive)
ide-haskell-repl, v0.1.10 (inactive)
json-schema, v0.1.15 (active)
language-arduino, v0.4.1 (active)
language-cpp14, v0.6.2 (active)
language-elm, v1.5.0 (active)
language-glsl, v2.0.1 (active)
language-haskell, v1.9.9 (active)
language-haxe, v0.5.3 (active)
language-lua, v0.9.11 (active)
language-moonscript, v1.7.1 (active)
language-ocaml, v1.1.2 (active)
language-racket, v0.4.0 (active)
language-rust, v0.4.7 (active)
language-scala, v1.1.6 (active)
language-sml, v0.6.0 (active)
language-valgrind, v0.1.0 (active)
linter, v1.11.18 (active)
linter-clang, v3.4.4 (active)
linter-cpplint, v1.0.1 (inactive)
linter-elm-make, v0.17.7 (active)
linter-emscripten, v0.1.1 (inactive)
linter-glsl, v2.0.5 (inactive)
linter-hlint, v0.5.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-lua, v1.0.2 (active)
linter-luaparse, v0.2.0 (active)
linter-markdown, v3.0.2 (active)
linter-moonscript, v0.1.2 (active)
linter-rust, v0.6.0 (active)
love-ide, v0.14.0 (inactive)
markdown-writer, v2.6.1 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
monokai-seti, v0.7.0 (inactive)
navigator-go, v1.1.3 (active)
nim, v0.3.6 (active)
omnisharp-atom, v0.30.7 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
project-manager, v3.2.3 (active)
racer, v0.20.0 (active)
rust-api-docs-helper, v0.5.1 (active)
rustfmt, v0.1.3 (active)
script, v3.10.1 (inactive)
seti-ui, v1.3.2 (inactive)
solarized-seti-ui, v0.8.6 (inactive)
switch-header-source, v0.20.0 (inactive)
tester-go, v2.0.2 (active)
todo-show, v1.7.0 (inactive)
tool-bar, v1.0.1 (active)
tool-bar-almighty, v0.8.1 (active)
yaml-sortkey, v0.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (active)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jamiltron** [comment]
I tried refreshing atom and nothing happened, but after restarting this problem seems to have resolved itself.
